language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

env:
  - DJANGO_SETTINGS_MODULE=mysite.settings

install:
  - pip install -r requirements.txt

script:
  - python manage.py check
  - python manage.py test
